language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: NnKhIxmsGXdZIDbKL/kqY+JwDTGWvOIeWR76n5Uf0qj+vZTc5Bgjsl1PhPuXTX2Ig5yI+VKYbp3vIroFGlgIlLW6yOnol8WtnVSNENxg8PxUYRM4sXtpqSLVyFiwV4LsswEOTcfBDmweqjVBHS/J4pJs+uqu6pdzHy3Y1Xq+hi+gUqSJ3IDd2SQ7Kdltqpfnbyr1FzDu2xTCGmIFVjhr3t4niQl4fUMT3YqB7zjVBEElrHy0AX7hnF9i4A6WoH4cq4dz7xiqvurHNS1G3ZCA5MGzGBxGNWWWLpIlOiyXqtCxYQzewUeXiI575FPa0QMsmP24OdkN3M7Gi98oaiQVvDSB4JQ2tnnOLJMKIs0LT+47s1ue62qYvsqZfP+LYH7Foux4bmgPbcNaaUOugRA4i9gKhMoq491odf06JMXTp6G2u1NDms4CsnQ9X4o1bX5zFzCtG5DEI1Lnq9jYxs6kGdXVBjVXCnWu9/ewYH07l+lzQC1Nyl7EtrMbg8poC8znKqHxJg/BBHszUC/e/qs6847UybTj5DlMUF2SJcoJg5PAJ1LCVlTWUFyM+G1pAqta5HJutRDViiW8R1Y21Ku1GExeowykXRI807a05+y+35z4f6W9pFLPaaBOvKqF5qcCw3b+KQmrQEjabqznQHFd9enTeJSP6VQyVu6I2+JPbck=
  app: serene-springs-88612
  on:
    repo: BlueLB84/blogpostslbv
